name: Windows Paraview Nightly

on:
  schedule:
    - cron: '0 2 * * *' # Run at 2 am

defaults:
  run:
    shell:
     powershell Invoke-Expression -Command "./share/spack/qa/windows_test_setup.ps1"; {0}


jobs:
  build-paraview-deps:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
      with:
        fetch-depth: 0
    - uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236
      with:
        python-version: 3.9
    - name: Install Python packages
      run: |
          python -m pip install --upgrade pip six pywin32 setuptools coverage
    - name: Build Test
      run: |
        spack compiler find
        spack external find cmake ninja win-sdk win-wdk wgl msmpi
        spack -d install -y --cdash-upload-url https://cdash.spack.io/submit.php?project=Spack+on+Windows --cdash-track Nightly --only dependencies paraview
        exit 0